import java.util.*;

/**
 * Generates a tray of lithium
 * Author: Samuel Roffey
 * Date: 07.10.2019
 */
public class GenerateLithium {
    //Two dimensional Array tray will store different int values of grading.
    int [][] tray = new int[5][3];
    //grading stores the int value generated by Random.
    private int grading = 0;
    //Randomly generates int numbers.
    private Random randomGenerator;
    /**
     * Constructor for objects of class GenerateLithium
     */
    public GenerateLithium() {
        randomGenerator = new Random();
        generateSample();   //for BuyLithium class
    }
    /**
     * Generates random numbers to populate array
     */
    public void generateSample() {
        for(int i = 0; i < 5; i++) {
            for (int j = 0; j < 3; j++) {
                grading = randomGenerator.nextInt(50 - 1) + 1;
                tray[i][j] = grading;
            }
        }
    }

    /**
     * Prints the tray array
     */
    public void printTray() {
        for(int i = 0; i < 5; i++) {
            for (int j = 0; j < 3; j++) {

                System.out.print(tray[i][j] + "||");
            }
            System.out.println();
        }
    }
}
